### ISSUE TITLE
Typo in omicsCiCdCodeBuildRole 

### ISSUE THREAD

**Issue by wlingkit** [aws-solutions-library-samples/guidance-for-bioinformatics-workflow-development-using-devops-on-aws#1]
The file publishing role created by the account bootstrap has "role" in its name. The resource specified in CdkDeployPolicy attached to the omicsCiCdCodeBuildRole is cdk-hnb659fds-file-publishing-<account_number>-<region>, missing the word "role" (omics-cicd-stack-commons.ts). This leads to a permission issue during the build step of CodePipeline.

**Comment by nbulsara** [comment]
The latest [commit](https://github.com/aws-solutions-library-samples/guidance-for-bioinformatics-workflow-development-using-devops-on-aws/commit/d47ca6a08726576eee61d24592b6454deb8934bd) should fix that issue, thank you for bringing it to our attention
